#!/bin/bash
#README.MD
#sr_edge_nodes.service
#sr_edge_nodes_service_watcher.service
sudo systemctl enable sr_mcureader.service
sudo systemctl enable sr_mcureset.service
sudo systemctl enable sr_orchestrator.service
sudo systemctl enable sr_rabbitmq_docker.service
#sr_restreamer.service
#sr_shutdown.service
#sr_shutdown.timer
sudo systemctl enable sr_subprocess_util.service
sudo systemctl enable sr_auto_wifi.service
