#!/bin/bash
#README.MD
#sr_edge_nodes.service
#sr_edge_nodes_service_watcher.service
sr_mcureader.service
sr_mcureset.service
sr_orchestrator.service
sr_rabbitmq_docker.service
#sr_restreamer.service
#sr_shutdown.service
#sr_shutdown.timer
sr_subprocess_util.service

